CREATE TABLE `Competency` (
  `competencyName` varchar(200) NOT NULL,
  PRIMARY KEY (`competencyName`)
)

insert into Competency(competencyName)
values
('Mobilises self and others to drive self-improvement'),
('Champions continuous improvement'),
('Developing networks and building and maintaining relationships'),
('Working within teams'),
('Developing self-awareness'),
('Managing yourself'),
('Continuing personal development'),
('Acting with integrity'),
('Mobilises people to drive business improvement & innovation'),
('Champions continuous improvement in self & others – creating a positive environment and encouraging contribution'),
('Managing performance'),
('Effective time management'),
('Promoting accountability'),
('Effective meetings'),
('Problem solving'),
('Supporting the strategy and vision'),
('Organisational awareness'),
('Cultural and ethical awareness'),
('Communicates effectively'),
('Influencing others'),
('Customer Focus and Stakeholder management'),
('Identifying the contexts for change'),
('Improvement and Innovation'),
('Making decisions'),
('Creating and Evaluating impact'),
('Framing the strategy'),
('Developing the strategy'),
('Implementing the strategy'),
('Embedding the strategy'),
('Demonstrates commercial awareness and behaviours'),
('Contributes to the ongoing development of new business to support Kainos’ growth ambitions'),
('Improves efficiency and effectiveness to drive profitability'),
('Manages risk to Kainos and the interest of our shareholders'),
('Promotes and adheres to Kainos process and policies'),
('Develops, communicates and promotes the Kainos vision and strategy'),
('Influencing the vision and beyond'),
('Influencing change and transformation'),
('Stakeholder management');

INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Apprentice', 'Effective time management', 'Understands role, tasks and deadlines and work towards these, escalating any issues where appropriate to People/Project Manager.', 'Setting Direction, Development and Accountability'),
('Apprentice', 'Promoting accountability', 'Accepts personal responsibility for quality and timelines of work set.', 'Setting Direction, Development and Accountability'),
('Apprentice', 'Effective meetings', 'Works to manage diary, commitments and ready to attend meetings on time.', 'Setting Direction, Development and Accountability'),
('Apprentice', 'Problem solving', 'Actively supports new initiatives and tries different ways of doing things, learning from others’ experiences.', 'Setting Direction, Development and Accountability'),
('Trainee', 'Effective time management', 'Plans time effectively to ensure deadlines are met, and seen to be honest, escalating in advance any issues with completing tasks within the specified time.', 'Setting Direction, Development and Accountability'),
('Trainee', 'Promoting accountability', 'Takes ownership of all responsibilities within own role and honours commitments to others and to Kainos.', 'Setting Direction, Development and Accountability'),
('Trainee', 'Effective meetings', 'Effectively manages diary, coming prepared for meetings and actively listen.', 'Setting Direction, Development and Accountability'),
('Trainee', 'Problem solving', 'Breaks down issues, and actively seeks further information and understanding.', 'Setting Direction, Development and Accountability'),
('Associate', 'Effective time management', 'Recognises how much time is required for different tasks and start to prioritise and communicate effectively within teams. Seeking appropriate support while supporting peers and junior team members.', 'Setting Direction, Development and Accountability'),
('Associate', 'Promoting accountability', 'Identifies commitments and proactively seeks responsibility in delivering towards the wider team and project objectives.', 'Setting Direction, Development and Accountability'),
('Associate', 'Effective meetings', 'Establishes effective meetings through setting an agenda and coming prepared and speaking on projects calls where appropriate. Follows up and delivers upon actions from meetings.', 'Setting Direction, Development and Accountability'),
('Associate', 'Problem solving', 'Makes suggestions for improvements to personal work and processes', 'Setting Direction, Development and Accountability'),
('Senior Associate', 'Effective time management', 'A strong ability to multitask and prioritise to deadlines, overcoming obstacles to ensure the work is completed within time. Researching and communicating in advance any barriers that may affect projects.', 'Setting Direction, Development and Accountability'),
('Senior Associate', 'Promoting accountability', 'Demonstrates individual responsibility for achieving objectives and able to articulate success, failures and proposing remedial actions.', 'Setting Direction, Development and Accountability'),
('Senior Associate', 'Effective meetings', 'Consistently prepared for meetings and effectively manages own diary for preparation and an agenda is set in advance. Actively seeks input from colleagues and challenges others where appropriate', 'Setting Direction, Development and Accountability'),
('Senior Associate', 'Problem solving', 'Processes and distils a variety of information to understand a problem fully while proposing options for solutions and building on the ideas of others.', 'Setting Direction, Development and Accountability'),
('Consultant', 'Effective time management', 'Develops effective systems to organise and track workload while, motivating and encouraging others to achieve planned results, delegating work to use people and resources to best effect. Ensuring colleagues are aware of any changing priorities and monitor progress', 'Setting Direction, Development and Accountability'),
('Consultant', 'Promoting accountability', 'Delegates authority to match responsibilities and holds staff accountable for agreed-upon commitments. Within immediate teams creates accountability by using experience and advice to guide others.', 'Setting Direction, Development and Accountability'),
('Consultant', 'Effective meetings', 'Sets an example of leading internal and external meetings through preparation, prioritisation, and considered agendas, ensuring any challenges and issues are discussed.', 'Setting Direction, Development and Accountability'),
('Consultant', 'Problem solving', 'Seeks the opinions and experiences of others to understand different approaches while thinking laterally about own work and encouraging creative problem solving.', 'Setting Direction, Development and Accountability');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Apprentice', 'Supporting the strategy and vision', 'Understands the Kainos Vision, Strategy and Principles.', 'Supporting and Delivering the Strategy'),
('Apprentice', 'Organisational awareness', 'Understands the organisation structure and the purpose of Kainos.', 'Supporting and Delivering the Strategy'),
('Apprentice', 'Cultural and ethical awareness', 'Possess general knowledge of local cultural differences and familiar with the Kainos policy towards Diversity and Inclusion.', 'Supporting and Delivering the Strategy'),
('Trainee', 'Supporting the strategy and vision', 'Recognises how to contribute to the wider organisational objectives and strategic principles.', 'Supporting and Delivering the Strategy'),
('Trainee', 'Organisational awareness', 'Pays attention to organisational information, how well we are doing and what is changing.', 'Supporting and Delivering the Strategy'),
('Trainee', 'Cultural and ethical awareness', 'Awareness of cultural differences and willingness to develop and grow understanding of global and cultural effectiveness.', 'Supporting and Delivering the Strategy'),
('Associate', 'Supporting the strategy and vision', 'Articulates individual contribution to the wider Kainos objectives and uses evidence by including SMART goals that align to the Capability/BU.', 'Supporting and Delivering the Strategy'),
('Associate', 'Organisational awareness', 'Clearly defines how individual personal performance can have an impact on the business achieving the vision and objectives.', 'Supporting and Delivering the Strategy'),
('Associate', 'Cultural and ethical awareness', 'Respects differences and promotes inclusion on a transactional level. Displays appropriate ethical behaviours and acknowledges own unconscious bias.', 'Supporting and Delivering the Strategy'),
('Senior Associate', 'Supporting the strategy and vision', 'Supports peers and team members in understanding the wider Kainos objectives and how we all have a role in Kainos’success.', 'Supporting and Delivering the Strategy'),
('Senior Associate', 'Organisational awareness', 'Recognises and reflects on how personal actions may have a wider impact on other people and teams.', 'Supporting and Delivering the Strategy'),
('Senior Associate', 'Cultural and ethical awareness', 'Demonstrates awareness and appreciation for the global multi-dimensional and diverse perspectives of our people. Provide a protective environment within immediate teams in which colleagues can escalate any issues while demonstrating impartial application of Kainos policies, procedure and practices.', 'Supporting and Delivering the Strategy'),
('Consultant', 'Supporting the strategy and vision', 'Balances own teams needs with wider organisational needs while translating the Vision and Strategy into practical and tangible goals.', 'Supporting and Delivering the Strategy'),
('Consultant', 'Organisational awareness', 'Effectively ensures immediate teams understand how their work contributes to and delivers organisational priorities.', 'Supporting and Delivering the Strategy'),
('Consultant', 'Cultural and ethical awareness', 'Consistently role models cultural effectiveness in the demonstration of ethical behaviours while understanding the value diversity brings to Kainos. Promoting diversity and inclusion within teams while adapting to the needs of our diverse people.', 'Supporting and Delivering the Strategy');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Apprentice', 'Demonstrates commercial awareness and behaviours', 'Understands the markets and sectors in which Kainos operates while acknowledging how role links in and has an impact on other teams and the business.', 'Commerciality and Risk'),
('Apprentice', 'Improves efficiency and effectiveness to drive profitability', 'Wiling to learn, and embrace new ideas, to improve processes and procedures.', 'Commerciality and Risk'),
('Apprentice', 'Promotes and adheres to Kainos process and policies', 'Cooperates with business processes completing accurately and honestly e.g., timesheets/EOY Review and travel requests.', 'Commerciality and Risk'),
('Trainee', 'Demonstrates commercial awareness and behaviours', 'Understands how the business generates income. Supporting the business by assisting in activities such as Recruitment events, Career fairs and Work experience mentoring. Keeps up to date with current trends relating to work.', 'Commerciality and Risk'),
('Trainee', 'Improves efficiency and effectiveness to drive profitability', 'Reviews current practices and constructive in implementing changes to own work.', 'Commerciality and Risk'),
('Trainee', 'Promotes and adheres to Kainos process and policies', 'Consistently cooperates with business processes completing accurately and honestly e.g., timesheets/EOY Review and travel requests.', 'Commerciality and Risk'),
('Associate', 'Demonstrates commercial awareness and behaviours', 'Comprehends the need for the business to generate additional income and respects that costs need to be managed. Recognises the contribution that role makes to the success of the business, consistently delivering to task deadlines.', 'Commerciality and Risk'),
('Associate', 'Improves efficiency and effectiveness to drive profitability', 'Acknowledges what is required to manage costs within the business. Considers and suggests ideas for improvements, sharing this feedback with others in a constructive manner.', 'Commerciality and Risk'),
('Associate', 'Promotes and adheres to Kainos process and policies', 'Constantly achieves personal productive utilisation targets. Appreciating how the team/project supports increased income for Kainos.', 'Commerciality and Risk'),
('Senior Associate', 'Demonstrates commercial awareness and behaviours', 'Demonstrates a clear understanding of how the business makes profit and how individual role effects profitability of the company. Respectfully challenges commercial decisions to contribute an increased profitability.', 'Commerciality and Risk'),
('Senior Associate', 'Improves efficiency and effectiveness to drive profitability', 'Manages and meets the expectations of customers without compromising budgets. Supports change in a constructive manner to help colleagues and stakeholders understand changes and why they have been introduced.', 'Commerciality and Risk'),
('Senior Associate', 'Promotes and adheres to Kainos process and policies', 'Understands the organisational structure of Kainos, reporting lines and can actively identify where key responsibilities lie.', 'Commerciality and Risk'),
('Consultant', 'Demonstrates commercial awareness and behaviours', 'Identifies potential new opportunities for Kainos to generate income and proactively takes action to progress. Understanding the commercial implications of changes in scope and negotiate with customers proactively. Able to look beyond the immediate problems/issues to see the impact on the bigger picture.', 'Commerciality and Risk'),
('Consultant', 'Improves efficiency and effectiveness to drive profitability', 'Uses financial information to find pragmatic new ways of saving cost/effort without reducing output. Review procedures or systems with immediate teams to identify improvements and simplify processes and decision making.', 'Commerciality and Risk'),
('Consultant', 'Promotes and adheres to Kainos process and policies', 'Recognise the impact of BU and company profitability and supports company decisions that affect +profit. Ensures own team are adhering to policies, processes, and procedures.', 'Commerciality and Risk');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Apprentice', 'Communicates effectively', 'Acts in a respectful manner in all forms of communication while being open and honest.Displays a positive approach when interacting with others.', 'Communicating and Influence'),
('Apprentice', 'Influencing others', 'Recognises influencing as a key skill required to work effectively with internal and external customers.', 'Communicating and Influence'),
('Apprentice', 'Customer Focus and Stakeholder management', 'Acts in accordance with the Kainos values demonstrating through own behaviours and interactions with colleagues and customers.', 'Communicating and Influence'),
('Trainee', 'Communicates effectively', 'Communicates own views in a clear and constructive manner, while listening to different views and considers all employees from various backgrounds.', 'Communicating and Influence'),
('Trainee', 'Influencing others', 'Observes team/colleagues influencing internally and externally and understands the benefits of adapting personal style to shape, motivate and influence effectively.', 'Communicating and Influence'),
('Trainee', 'Customer Focus and Stakeholder management', 'Understands who our customers are and what problems the team is trying to solve.', 'Communicating and Influence'),
('Associate', 'Communicates effectively', 'Involved at meetings, asking questions, listening and develops and presents a well-reasoned point of view. Remaining communicative and clear in own thoughts and ideas when approached by others, giving consideration to the communication needs of other staff and customers.', 'Communicating and Influence'),
('Associate', 'Influencing others', 'Demonstrates influencing skills internally and able to communicate points clearly and open to feedback from others.', 'Communicating and Influence'),
('Associate', 'Customer Focus and Stakeholder management', 'Demonstrates how to participate in stakeholder management, escalates effectively, and strives to provide a quality service and showcase Kainos positively.', 'Communicating and Influence'),
('Senior Associate', 'Communicates effectively', 'Recognises and respect that communication is a two-way process and demonstrate effective questioning and active listening skills to achieve this. Confidently handles challenging conversations and is clear and constructive in response.', 'Communicating and Influence'),
('Senior Associate', 'Influencing others', 'Persuades and influences with sound rationale argument ‘appealing to others’ interest or reason to gain support.', 'Communicating and Influence'),
('Senior Associate', 'Customer Focus and Stakeholder management', 'Authentic in stakeholder relationships and take pride in being inclusive and trustworthy while keeping promises made with customers. Responds honestly and promptly to customer requests and whenever possible within agreed timeframes.', 'Communicating and Influence'),
('Consultant', 'Communicates effectively', 'Uses communication to create a shared sense of purpose and direction. Adapting own style to effectively communicate and able to demonstrate this when difficult conversations have a positive outcome.', 'Communicating and Influence'),
('Consultant', 'Influencing others', 'Acts as an influential and effective member of multi-disciplinary teams or projects. Initiate’s collaboration and actively encourages people to cooperate in initiatives where they can add value.', 'Communicating and Influence'),
('Consultant', 'Customer Focus and Stakeholder management', 'Assesses customer needs accurately by listening and applying sensitive questioning. Managing customer expectations in relation to scope of work and are honest in what can and cannot be achieved within timescales. Confident in negotiating with customers to reflect changes in scope of work.', 'Communicating and Influence');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Developing self-awareness', 'Reflects on how factors such as own values, prejudices and emotions influences own judgement, behaviour, and self-belief. Uses feedback from appraisals and other sources to consider personal impact and changes behaviour. Understands personal sources of stress and wellbeing.', 'Personal Performance'),
('Manager', 'Managing yourself', 'Plans and manages own time effectively and fulfils work requirements and commitments to a high standard, without compromising own health and wellbeing. Remains calm and focused under pressure.', 'Personal Performance'),
('Manager', 'Continuing personal development', 'Proactively manages self and career and identifies personal learning needs plan and completes a broad range of formal and informal learning opportunities by taking responsibility for own personal development and seeking opportunities for learning. Strives to put learning into practice. Clearly demonstrates that leadership and technical skills are equally valued.', 'Personal Performance'),
('Manager', 'Acting with integrity', 'Behaves in an open, honest, and inclusive manner, upholding personal and organisational ethics and values. Shows respect for the needs of others and promotes equality and diversity.', 'Personal Performance'),
('Principal', 'Developing self-awareness', 'Reflects on own interactions with a wide and diverse range of individuals and groups from within and beyond immediate service/organisation. Challenges and refreshes own values, beliefs, leadership styles and approaches. Overtly role models the giving and receiving of feedback.', 'Personal Performance'),
('Principal', 'Managing yourself', 'Successfully manages a range of personal and organisational demands and pressures. Demonstrates tenacity and resilience. Overcomes setbacks where goals cannot be achieved and quickly refocuses. Is visible and accessible to others.', 'Personal Performance'),
('Principal', 'Continuing personal development', 'Acts as an exemplar for others in managing continuous personal development. Facilitates the development of a learning culture.Identifies tangible, objective business improvements and benefits when planning development activities and identifies and tracks the se through metrics, to demonstrate impact on business results.', 'Personal Performance'),
('Principal', 'Acting with integrity', 'Creates an open, honest, and inclusive culture in accordance with clear principles and values. Ensures equity of access to services and creates an environment where people from all backgrounds can excel.', 'Personal Performance'),
('Leadership Community', 'Developing self-awareness', 'An exemplary role model of self-awareness and welcomes feedback openly. A strong advocate and voice for building a culture of self-development and seen to set the tone for effective leadership at a senior level.', 'Personal Performance'),
('Leadership Community', 'Managing yourself', 'Confident and independent in own personal impact and recognises an influence on others beyond immediate teams. Goals are aligned to strategic objectives and Kainos values. Champions self and others for equality, diversity, and inclusion.', 'Personal Performance'),
('Leadership Community', 'Continuing personal development', 'Role models continuous learning and self-development, evaluating own effectiveness and growth and planning further development. Progresses in the right direction for self and Kainos through strong personal ownership.', 'Personal Performance'),
('Leadership Community', 'Acting with integrity', 'Assures standards of integrity are maintained across the business and communicates the importance of always adopting an ethical and inclusive approach.', 'Personal Performance');

INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Developing self-awareness', 'Reflects on how factors such as own values, prejudices and emotions influences own judgement, behaviour, and self-belief. Uses feedback from appraisals and other sources to consider personal impact and changes behaviour. Understands personal sources of stress and wellbeing.', 'Personal Performance'),
('Manager', 'Managing yourself', 'Plans and manages own time effectively and fulfils work requirements and commitments to a high standard, without compromising own health and wellbeing. Remains calm and focused under pressure.', 'Personal Performance'),
('Manager', 'Continuing personal development', 'Proactively manages self and career and identifies personal learning needs plan and completes a broad range of formal and informal learning opportunities by taking responsibility for own personal development and seeking opportunities for learning. Strives to put learning into practice. Clearly demonstrates that leadership and technical skills are equally valued.', 'Personal Performance'),
('Manager', 'Acting with integrity', 'Behaves in an open, honest, and inclusive manner, upholding personal and organisational ethics and values. Shows respect for the needs of others and promotes equality and diversity.', 'Personal Performance'),
('Principal', 'Developing self-awareness', 'Reflects on own interactions with a wide and diverse range of individuals and groups from within and beyond immediate service/organisation. Challenges and refreshes own values, beliefs, leadership styles and approaches. Overtly role models the giving and receiving of feedback.', 'Personal Performance'),
('Principal', 'Managing yourself', 'Successfully manages a range of personal and organisational demands and pressures. Demonstrates tenacity and resilience. Overcomes setbacks where goals cannot be achieved and quickly refocuses. Is visible and accessible to others.', 'Personal Performance'),
('Principal', 'Continuing personal development', 'Acts as an exemplar for others in managing continuous personal development. Facilitates the development of a learning culture.Identifies tangible, objective business improvements and benefits when planning development activities and identifies and tracks the se through metrics, to demonstrate impact on business results.', 'Personal Performance'),
('Principal', 'Acting with integrity', 'Creates an open, honest, and inclusive culture in accordance with clear principles and values. Ensures equity of access to services and creates an environment where people from all backgrounds can excel.', 'Personal Performance'),
('Leadership Community', 'Developing self-awareness', 'An exemplary role model of self-awareness and welcomes feedback openly. A strong advocate and voice for building a culture of self-development and seen to set the tone for effective leadership at a senior level.', 'Personal Performance'),
('Leadership Community', 'Managing yourself', 'Confident and independent in own personal impact and recognises an influence on others beyond immediate teams. Goals are aligned to strategic objectives and Kainos values. Champions self and others for equality, diversity, and inclusion.', 'Personal Performance'),
('Leadership Community', 'Continuing personal development', 'Role models continuous learning and self-development, evaluating own effectiveness and growth and planning further development. Progresses in the right direction for self and Kainos through strong personal ownership.', 'Personal Performance'),
('Leadership Community', 'Acting with integrity', 'Assures standards of integrity are maintained across the business and communicates the importance of always adopting an ethical and inclusive approach.', 'Personal Performance');

INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Mobilises people to drive business improvement & innovation', 'Supports others in delivering high quality services and excellence by supporting mobilising teams and contributing to business improvement.', 'Working with Others'),
('Manager', 'Champions continuous improvement in self & others – creating a positive environment and encouraging contribution', 'Seeks and acknowledges the views and inputs of others. Shows respect for the contributions and challenges of others through positive and constructive feedback.', 'Working with Others'),
('Manager', 'Managing performance', 'Uses information and data about performance to identify improvements which will strengthen services.', 'Working with Others'),
('Manager', 'Developing networks and building and maintaining relationships', 'Identifies where working and cooperating with others can result in better services. Endeavours to work collaboratively. Communicates with and listens to others, recognising different perspectives. Empathises and considers the needs and feelings of others. Gains and maintains trust and support.', 'Working with Others'),
('Manager', 'Working within teams', 'Understands roles, responsibilities, and purpose within the team. Adopts a collaborative approach and respects team decisions.', 'Working with Others'),
('Principal', 'Mobilises people to drive business improvement & innovation', 'Motivates and coaches’ individuals and teams to strengthen their performance and assist with developing their own capabilities and skills. Aligns individual development needs with service goals.', 'Working with Others'),
('Principal', 'Champions continuous improvement in self & others – creating a positive environment and encouraging contribution', 'Integrates the contributions of a diverse range of stakeholders, being open and honest about the extent to which contributions can be based upon. Challenges others to provide stronger feedback and drive continuous improvement.', 'Working with Others'),
('Principal', 'Managing performance', 'Establishes rigorous performance measures. Holds self, individuals, and teams to account for achieving performance standards. Challenges when service expectations are not being met and takes corrective action.', 'Working with Others'),
('Principal', 'Developing networks and building and maintaining relationships', 'Identifies and builds effective networks with a range of influential stakeholders internal and external to the organisation. Builds and nurtures trusting relationships at all levels within and across services and organisational boundaries.', 'Working with Others'),
('Principal', 'Working within teams', 'Takes on recognised leadership roles within the organisation. Builds high performing inclusive teams that contribute to productivity and efficiencies. Promotes autonomy and empowerment and maintains a sense of optimism and confidence.', 'Working with Others'),
('Leadership Community', 'Mobilises people to drive business improvement & innovation', 'Inspires and supports the business to mobilise diverse teams that are committed to and aligned with organisational values and goals. Engages with influencers to deliver joined up services.', 'Working with Others'),
('Leadership Community', 'Champions continuous improvement in self & others – creating a positive environment and encouraging contribution', 'Creates systems which encourage contribution throughout the organisation. Invites contribution from different regions, sectors, and business units to bring about consistent improvements.', 'Working with Others'),
('Leadership Community', 'Managing performance', 'Successfully accountable for the direction of the wider business on creating performance standards and recognises business areas that require focus and adapts approach to meet the demands and needs of employees, customers, and services.', 'Working with Others'),
('Leadership Community', 'Developing networks and building and maintaining relationships', 'Works across boundaries creating networks which facilitate high levels of collaboration within and across organisations and sectors. Builds and maintains sustainable strategic alliances across the system and other sectors. Has high impact when interacting with others at all levels.', 'Working with Others'),
('Leadership Community', 'Working within teams', 'Contributes and leads senior teams. Enables others to take on leadership responsibilities, building high level leadership capability and capacity from a diverse range of backgrounds.', 'Working with Others');

INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Identifying the contexts for change', 'Understands the range of factors which determine why changes are made and supports Kainos senior leaders to deliver key messages.', 'Setting Direction, Development and Accountability'),
('Manager', 'Improvement and Innovation', 'Gathers data and information about aspects of the business, analyses evidence and uses this knowledge to suggest changes that will improve services in the future. Questions established practices which do not add value. Puts forward creative suggestions to improve the quality of service provided.', 'Setting Direction, Development and Accountability'),
('Manager', 'Making decisions', 'Consults with others and contributes to decisions including the future direction/vision of own business area or projects.', 'Setting Direction, Development and Accountability'),
('Manager', 'Creating and Evaluating impact', 'Assesses the effects of change on service delivery and customer outcomes. Makes recommendations for future improvements.', 'Setting Direction, Development and Accountability'),
('Principal', 'Identifying the contexts for change', 'Actively seeks to learn about internal and external factors which will impact on the business. Interprets the meaning of these for Kainos and incorporates these into business plans and actions.', 'Setting Direction, Development and Accountability'),
('Principal', 'Improvement and Innovation', 'Understands the complex interdependencies across a range of services. Applies knowledge to set future direction. Challenges colleagues’ thinking to find better and more effective ways of delivering services and quality. Accesses creativity and innovation from relevant individuals and groups.', 'Setting Direction, Development and Accountability'),
('Principal', 'Making decisions', 'Remains accountable for making timely decisions in complex situations. Modifies decisions and flexes direction when faced with new information or changing circumstances', 'Setting Direction, Development and Accountability'),
('Principal', 'Creating and Evaluating impact', 'Identifies gains which can be applied elsewhere in the business and incorporates these into operational / capability / business plans. Disseminates learning from changes which have been introduced.', 'Setting Direction, Development and Accountability'),
('Leadership Community', 'Identifying the contexts for change', 'Synthesises knowledge from a broad range of sources to identify future challenges and imperatives that will create the need for change. Influences the context for change in the best interests of our people, our customers, and our business.', 'Setting Direction, Development and Accountability'),
('Leadership Community', 'Improvement and Innovation', 'Uses knowledge, evidence,and experience of national and international developments in technology and our consumers to influence the future development of Kainos and our services. Drives a culture of innovation and improvement. Integrates radical and innovative approaches into strategic plans to make Kainos world class in the provision of technology services.', 'Setting Direction, Development and Accountability'),
('Leadership Community', 'Making decisions', 'Ensures that corporate decision-making is conducted with appropriate rigour and takes account of the full range of factors impinging on the future direction of the organisation and the wider business. Can operate without all the facts. Takes unpopular decisions when in the best interests of Kainos in the long term.', 'Setting Direction, Development and Accountability'),
('Leadership Community', 'Creating and Evaluating impact', 'Synthesises learning arising from changes which have been introduced and incorporates these into strategic plans. Shares learning with the wider business.', 'Setting Direction, Development and Accountability');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Framing the strategy', 'Strategic awareness including an understanding and knowledge of how role and those within in immediate team fit with and support delivery of the organisational objectives.', 'Supporting and Delivering the Strategy'),
('Manager', 'Developing the strategy', 'Feeds in ideas and knowledge from immediate teams and supports the senior leaders in developing a strategy.', 'Supporting and Delivering the Strategy'),
('Manager', 'Implementing the strategy', 'Support, develop and implement the strategy in immediate teams.', 'Supporting and Delivering the Strategy'),
('Manager', 'Embedding the strategy', 'Passionately advocates the strategy and vision and translates this into action and opportunities within immediate teams. Understands the need for OKR’s/KPI’s and own role in supporting and shaping in relation to immediate teams.', 'Supporting and Delivering the Strategy'),
('Principal', 'Framing the strategy', 'Encourages and demonstrates creative, lateral, critical and systems-based thinking when framing the strategy.', 'Supporting and Delivering the Strategy'),
('Principal', 'Developing the strategy', 'Engages with key individuals and groups to formulate strategic plans that aligns with the wider Kainos objectives. Identify organisational change requirements and ensure they are understood for organisational readiness decisions.', 'Supporting and Delivering the Strategy'),
('Principal', 'Implementing the strategy', 'Ensures that the strategic plans are translated into workable operational plans, identifying risks, critical success factors and evaluation methods. Championing change despite personal resistance to demonstrate the ability to support and lead other through change.', 'Supporting and Delivering the Strategy'),
('Principal', 'Embedding the strategy', 'Creates a consultative organisational culture to support delivery of the strategy and to drive strategic change within the wider business. Sets direction and priorities through KPI’s and monitors success.', 'Supporting and Delivering the Strategy'),
('Leadership Community', 'Framing the strategy', 'Takes account of the culture, history, and long-term strategic direction for Kainos. Critically reviewing relevant thinking, ideas and best practice and applies whole systems thinking to conceptualise a strategy in line with the vision.', 'Supporting and Delivering the Strategy'),
('Leadership Community', 'Developing the strategy', 'Integrates the views of a broad range of stakeholders to develop a coherent, joined up and sustainable strategy for own domain. Assesses organisational readiness for change. Manages the risks, political sensitivities and environmental uncertainties involved.', 'Supporting and Delivering the Strategy'),
('Leadership Community', 'Implementing the strategy', 'Responds constructively to challenge. Puts systems, structures, processes, resources, and plans in place to deliver the strategy. Establishes accountabilities and holds people in local, regional, and national structures to account for jointly delivering strategic and operational plans. Demonstrates flexibility when change is required.', 'Supporting and Delivering the Strategy'),
('Leadership Community', 'Embedding the strategy', 'Enables and supports the conditions and culture needed to sustain changes integral to the successful delivery of the strategy. Keeps momentum alive by reinforcing key messages, monitoring progress, and recognising where the strategy has been embraced by others. Evaluates outcomes and uses learnings to adapt strategic and operational plans. Aligns KPI’s across the business and reports on progress to ensure continued progress.', 'Supporting and Delivering the Strategy');

INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Demonstrates commercial awareness and behaviours', 'Aware of the importance of effective commercial behaviours and the needs of the business. Identifies and ensures that personal objectives are focussed on innovative solutions to achieve commercial outcomes and objectives as well as contributing to our growth ambitions. Recognises when products or services are not being  delivered to the required level of quality or standard and takes appropriate action.', 'Commerciality and Risk'),
('Manager', 'Contributes to the ongoing development of new business to support Kainos’ growth ambitions', 'Contributes to development of new business through involvement in BD process, for example, bid/proposal writing, customer presentations, pricing solutions. Establishes trusted customer relationships and adds value by helping and advising customers in areas beyond current project work, identifying possible areas where additional Kainos business can be generated.', 'Commerciality and Risk'),
('Manager', 'Improves efficiency and effectiveness to drive profitability', 'Looks to support and drive efficiencies and profitability through immediate team. Reviews processes within own teams and challenges through the right behaviours and channels to support the overall commercial objectives.', 'Commerciality and Risk'),
('Manager', 'Manages risk to Kainos and the interest of our shareholders', 'Understands and protects Kainos from risks associated with contractual commitments. Takes a balanced risk and reward view to activities and commitments while managing quality and Kainos interests.', 'Commerciality and Risk'),
('Manager', 'Promotes and adheres to Kainos process and policies', 'Supports and aligns to Kainos policies and processes escalating or challenging where appropriate. Ensures compliance across own team.', 'Commerciality and Risk'),
('Principal', 'Demonstrates commercial awareness and behaviours', 'Recognises commercial opportunities and where necessary seeks support in converting those opportunities into income. Leads on the awareness to protect margin through various means by setting the tone within own teams and BU. Encouraging others to challenge profit, spend and process. Creates value add propositions to support growth and negotiates fair deals for customers and services both internal and external.', 'Commerciality and Risk'),
('Principal', 'Contributes to the ongoing development of new business to support Kainos’ growth ambitions', 'Takes ownership and responsibility of creating and executing a strategy to develop new business in an area of expertise, in accordance with agreed targets and OKRs. Pro-actively promotes Kainos externally, in line with relevant field of expertise, identifying and fostering leads and opportunities for Kainos to generate new business. Coaches, motivates and encourages colleagues to develop new BD skills and provides the opportunity for colleagues to excel in this field.', 'Commerciality and Risk'),
('Principal', 'Improves efficiency and effectiveness to drive profitability', 'Leads the creation of business cases while championing efficiencies through innovation and change. Challenges others to work differently by reducing the effort within Kainos internally and engages customers in commercial conversations to maximise profit.', 'Commerciality and Risk'),
('Principal', 'Manages risk to Kainos and the interest of our shareholders', 'Promotes all aspects of the Kainos brand both internally and externally. Sets and delivers upon goals that directly impact the financial stability of Kainos. Implements appropriate mechanisms to measure progress towards commercial results, identifies shortfalls and risks and escalates as necessary.', 'Commerciality and Risk'),
('Principal', 'Promotes and adheres to Kainos process and policies', 'Influences the Kainos processes and policies ensuring teams are consistently managed against these.', 'Commerciality and Risk'),
('Leadership Community', 'Demonstrates commercial awareness and behaviours', 'Develops teams focussed on maximising commercial value for Kainos who are focused on pace, execution, and decisiveness. Builds a culture of challenging discretionary spend to ensure alignment to Kainos and organisational objectives, as well as seeking and driving opportunities that will deliver increased growth and profit.', 'Commerciality and Risk'),
('Leadership Community', 'Contributes to the ongoing development of new business to support Kainos’ growth ambitions', 'Identifies and leads significant new business streams that positively deliver growth for Kainos, for example, running a major practice or region and responsible for generating new business that will achieve agreed targets and OKRs. Leading and inspiring a team with devolved responsibility to deliver success. With an entrepreneurial mindset, yet balanced against robust business plans, creating and driving new business initiatives that support growth, staff development and market differentiation.', 'Commerciality and Risk'),
('Leadership Community', 'Improves efficiency and effectiveness to drive profitability', 'Independently accountable for leading and executing the business plan while building commercial acumen across the wider business and our customers, including introducing incremental and ongoing change and innovation to drive improvements that impact profitability.', 'Commerciality and Risk'),
('Leadership Community', 'Manages risk to Kainos and the interest of our shareholders', 'Ensure that commercial considerations and risks are fully considered when defining strategic priorities and plans. Seeks opportunities to expand the Kainos brand through accountability for leading companywide initiatives that will bolster the Kainos brand positively. Confidence to take calculated and assessed risks to support growth objectives.', 'Commerciality and Risk'),
('Leadership Community', 'Promotes and adheres to Kainos process and policies', 'Creates and establishes high performance and effective working across Kainos by leading consistent application of processes and setting new direction for process including constructive challenge in the interests of continuous improvement.', 'Commerciality and Risk');


INSERT INTO BandCompetency(bandName, competencyName, description, competencyMainName)
values
('Manager', 'Develops, communicates and promotes the Kainos vision and strategy', 'Provides feedback and support in communicating the vision, and advocates within immediate teams.', 'Communicating and Influence'),
('Manager', 'Influencing the vision and beyond', 'Credible communicator, displaying authenticity and adapting influencing style for different audiences.', 'Communicating and Influence'),
('Manager', 'Influencing change and transformation', 'Articulates the need for changes to processes and systems, acknowledging the impact on people and services.', 'Communicating and Influence'),
('Manager', 'Stakeholder management', 'Applies and adapts various approaches to stakeholder management through influencing and negotiating to maximise business for Kainos by developing and maintaining internal and external networks.', 'Communicating and Influence'),
('Principal', 'Develops, communicates and promotes the Kainos vision and strategy', 'Engages people across the business in the vision and strategy and demonstrates a high degree of emotional intelligence and transitioning between influencing style to suit the audience.', 'Communicating and Influence'),
('Principal', 'Influencing the vision and beyond', 'Communicates the vision and rationale for change and modernisation through engaging and facilitating others to work collaboratively to achieve real change.', 'Communicating and Influence'),
('Principal', 'Influencing change and transformation', 'Energises others to drive change that will improve Kainos by actively managing the change process, drawing on models of effective change management. Recognises and addresses the impact of change on people and services.', 'Communicating and Influence'),
('Principal', 'Stakeholder management', 'Actively builds and maintains internal and external networks to achieve progress on objectives and shared interests through a robust understanding of Kainos’s stakeholder landscape, interactions, issues,and linkages. Engages effectively on complex issues with hostile stakeholders.', 'Communicating and Influence'),
('Leadership Community', 'Develops, communicates and promotes the Kainos vision and strategy', 'Develops and clearly communicates the vision and strategy for own business area in a way that engages and empowers others. Uses enthusiasm and energy to inspire others and encourage joint ownership of the vision. Anticipates and constructively addresses challenge.', 'Communicating and Influence'),
('Leadership Community', 'Influencing the vision and beyond', 'Actively participates in and leads on debates about the future of Kainos and our related services. Manages political interests, balancing tensions between organisational aspirations and the wider environment. Shapes and influences local, regional, and national priorities and agendas.', 'Communicating and Influence'),
('Leadership Community', 'Influencing change and transformation', 'Inspires others to take bold action and make important advances in how services are delivered. Removes organisational obstacles to change and creates new structures and processes to facilitate transformation.', 'Communicating and Influence'),
('Leadership Community', 'Stakeholder management', 'Proactively creates, maintains,and promotes a strong network of connections with colleagues across Kainos and external stakeholders. Creates an inclusive environment while maximising opportunities for teams to engage with a variety of partners and stakeholders.', 'Communicating and Influence');
