DELETE FROM Training WHERE 1=1;
DROP TABLE BandTraining;
DROP TABLE Training;

CREATE TABLE `Training` (
  `trainingID` smallint NOT NULL AUTO_INCREMENT,
  `trainingName` varchar(255) NOT NULL,
  `trainingType` enum('DEVELOPMENT_PROGRAMME','PROFESSIONAL_SKILLS','TECHNICAL_SKILLS') NOT NULL,
  `sharepointURL` varchar(150) NOT NULL,
  PRIMARY KEY (`trainingID`)
);

CREATE TABLE `BandTraining` (
  `bandTrainingID` smallint NOT NULL AUTO_INCREMENT,
  `bandName` varchar(50) NOT NULL,
  `trainingID` smallint NOT NULL,
  PRIMARY KEY (`bandTrainingID`),
  KEY `bandName` (`bandName`),
  KEY `trainingID` (`trainingID`),
  CONSTRAINT `BandTraining_ibfk_1` FOREIGN KEY (`bandName`) REFERENCES `Band` (`bandName`) ON DELETE CASCADE,
  CONSTRAINT `BandTraining_ibfk_2` FOREIGN KEY (`trainingID`) REFERENCES `Training` (`trainingID`) ON DELETE CASCADE
);

INSERT INTO Training VALUES (1, 'Mindset Modules', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Mindset.aspx');
INSERT INTO Training VALUES (2, 'Virtual Effective Manager Series', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Effective-Manager.aspx');
INSERT INTO Training VALUES (3, 'Coaching - to help make a difference', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Coaching-%E2%80%93-To-help-make-a-Difference.aspx');
INSERT INTO Training VALUES (4, 'Intro To Remote Working', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Intro-to-Remote-Working.aspx');
INSERT INTO Training VALUES (5, 'Effective Time Management', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Time-Management.aspx');
INSERT INTO Training VALUES (6, 'Discovering Your Personal Brand', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Discovering-your-Personal-Brand.aspx');
INSERT INTO Training VALUES (7, 'Having Courageous Conversations', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Crucial-Conversations.aspx');
INSERT INTO Training VALUES (8, 'Making Effective Decisions', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Effective-Decision-Making.aspx');
INSERT INTO Training VALUES (9, 'Effective Meetings', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Effective-Meetings.aspx');
INSERT INTO Training VALUES (10, 'Interpersonal Skills', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Interpersonal-Skills.aspx');
INSERT INTO Training VALUES (11, 'Customer Service', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Customer-Service.aspx');
INSERT INTO Training VALUES (12, 'Leading Change', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Leading-Change.aspx');
INSERT INTO Training VALUES (13, 'Managing Change', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Managing-Change.aspx');
INSERT INTO Training VALUES (14, 'Effective Decision Making', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Effective-Decision-Making.aspx');
INSERT INTO Training VALUES (15, 'Interviewer Skills', 'PROFESSIONAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Interviewer-Skills.aspx');

INSERT INTO Training VALUES (16, 'WORKDAY FINANCIALS 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Workday%201O1%20-%20Financials.aspx');
INSERT INTO Training VALUES (17, 'WORKDAY HCM 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Workday%201O1%20-%20HCM.aspx');
INSERT INTO Training VALUES (18, 'WORKDAY PAYROLL 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Payroll-101.aspx');
INSERT INTO Training VALUES (19, 'SMART 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Smart%201O1.aspx');
INSERT INTO Training VALUES (20, 'TEST MANAGEMENT 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Testing-101.aspx');
INSERT INTO Training VALUES (21, 'PRISM 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/PRISM(1).aspx');
INSERT INTO Training VALUES (22, 'WORKDAY 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Workday-101.aspx');
INSERT INTO Training VALUES (23, 'WORKDAY EXTEND 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Workday-Extend-101.aspx?Mode=Edit');
INSERT INTO Training VALUES (24, 'ADAPTIVE PLANNING 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Adaptive-Insights-101(1).aspx');
INSERT INTO Training VALUES (25, 'SMART PAYROLL 101', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/WDA-Smart-Payroll-101.aspx');
INSERT INTO Training VALUES (26, 'MS Excel for Workday Consultants 102', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Excel-102.aspx');
INSERT INTO Training VALUES (27, 'OPERATIONAL MANAGEMENT FOR EMs / PMs 102', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Kimble-Operations-for-Engagement-Managers.aspx');
INSERT INTO Training VALUES (28, 'CROSS SELLING & UP-SELLING 102', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Smart-Customer-Success-Programme.aspx');
INSERT INTO Training VALUES (29, 'AMS + SALES ENABLEMENT 102', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Accelerate---Sales-Enablement.aspx');
INSERT INTO Training VALUES (30, 'Pre-certification - PROJECTS (PSA) 103', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Intro%20to%20PSA.aspx');
INSERT INTO Training VALUES (31, 'Pre-certification - ABSENCE 103', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Intro%20to%20Absence.aspx');
INSERT INTO Training VALUES (32, 'Pre-certification - TIME TRACKING 103', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Intro-to-Time-Tracking(1).aspx');
INSERT INTO Training VALUES (33, 'Pre-certification - LEARNING 103', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Precertification-in-LEARNING.aspx');
INSERT INTO Training VALUES (34, 'Pre-certification - BENEFITS 103', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Pre-Certification-Benefits.aspx');
INSERT INTO Training VALUES (35, 'Pre-Sales Orientations (PS11)', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Pre-Sales-Orientation.aspx');
INSERT INTO Training VALUES (36, 'JMeter performance', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Performance-Testing--Introduction-to-jmeter.aspx');
INSERT INTO Training VALUES (37, 'Java for Testers', 'TECHNICAL_SKILLS', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Java-for-Testers.aspx');

INSERT INTO Training VALUES (38, 'Consultant Development Programme (CDP)', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Consultant-Development-Programme-(CDP).aspx?web=1');
INSERT INTO Training VALUES (39, 'Emerging Leaders Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Management-Development-Programme-(MDP).aspx?web=1');
INSERT INTO Training VALUES (40, 'Inspiring Leaders Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Inspiring-Leaders-Programme.aspx');
INSERT INTO Training VALUES (41, 'Engineering EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Engineering-Programme.aspx');
INSERT INTO Training VALUES (42, 'Platforms EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Platforms-Programme.aspx');
INSERT INTO Training VALUES (43, 'Data EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Data-Programme.aspx');
INSERT INTO Training VALUES (44, 'UX EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/UX-Programme.aspx');
INSERT INTO Training VALUES (45, 'Business Analyst EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/L%26D/SitePages/Business-Analyst.aspx');
INSERT INTO Training VALUES (46, 'Workday EL Programme', 'DEVELOPMENT_PROGRAMME', 'https://kainossoftwareltd.sharepoint.com/sites/WorkSmartSharePoint/SitePages/Workday-Entry-Level.aspx');

INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 1);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 2);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 3);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 4);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 4);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 4);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 4);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 5);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 5);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 5);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 5);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 6);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 7);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 7);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 7);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 7);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 7);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 8);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 8);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 8);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 8);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 8);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 9);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 9);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 9);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 9);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 10);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 10);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 10);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 10);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 11);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 11);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 11);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 11);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 12);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 12);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 13);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 13);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 14);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 14);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 14);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 14);

INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 16);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 17);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 18);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 19);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 20);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 21);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 22);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 23);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 24);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 25);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 26);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 27);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 28);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 28);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 28);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 28);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 30);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 31);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 32);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 33);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 34);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 35);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 35);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 35);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 35);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 35);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 36);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 36);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 36);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 36);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 36);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 37);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 37);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 37);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 37);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 37);

INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 38);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 39);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 39);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Leadership Community', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Principal', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Manager', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Consultant', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Senior Associate', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Associate', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 40);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 41);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 41);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 42);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 42);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 43);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 43);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 44);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 44);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 45);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 45);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Trainee', 46);
INSERT INTO BandTraining (bandName, trainingID) VALUES ('Apprentice', 46);